---
- hosts: all
  vars:
    entrypoint: "/usr/sbin/asterisk -C /etc/asterisk/asterisk.conf"
    volumes: [
        {
            name: "config", path: "/.volumes/config", readOnly: true,
            links: ["/etc/asterisk"]
        }
    ]

    packages: [
        "asterisk",
    ]

    exposed: [
        { port: 4569, proto: "udp" },
        { port: 5060, proto: "udp" },
        { port: 10000, count: 10000, proto: "udp" }
    ]

  roles:
    - rkt-ansibuild